version: "3.9"
services:
  app:
    build: .
    container_name: t3-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: postgres:15
    container_name: t3-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: t3db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
